# Generated by Django 4.2.5 on 2023-09-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_appstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appstate',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
    ]
