# Generated by Django 4.2.5 on 2023-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_appstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appstate',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Declined'), (3, 'Pending')], default=3),
        ),
    ]
