# Generated by Django 4.2.5 on 2023-09-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_application_appstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appuniname',
            field=models.TextField(choices=[('BUET', 'Buet'), ('DUET', 'Duet'), ('RUET', 'Ruet'), ('CUET', 'Cuet'), ('KUET', 'Kuet'), ('SEC', 'Sec'), ('MIST', 'Mist'), ('MEC', 'Mec'), ('IUT', 'Iut')]),
        ),
    ]
